### ISSUE TITLE
Large hApp installations fail due to timeout

### ISSUE THREAD

**Issue by jost-s** [holochain/tryorama#106]
When installing a larger hApp via the function `installAgentsHapps` using paths, a timeout prevents the installation from succeeding.

[As discussed in the Holochain repo](https://github.com/holochain/holochain/issues/966), there needs to be a setting for the Holochain client's timeout.

**Comment by pospi** [comment]
Any chance we can get this in the next release? It seems like a pretty straightforward fix to expose an env var to allow configuring this. Still being blocked on getting my integration tests in working order.

**Comment by jost-s** [comment]
Hi @pospi, as [I wrote on discord](https://discord.com/channels/727959104777224303/776952534873931806/954439250240233582), we're working on a bigger refactoring of Tryorama. This fix will for sure make it into the next release.

If you're missing any feature from Tryorama, please comment on discord.

**Comment by pospi** [comment]
No worries, I added a [temporary workaround](https://github.com/holo-rea/holo-rea/commit/bfde90bd5e634ca6a4a0b36eaa4e4d9fcd9ff472) for now.

Actually thinking about it after patching, it seems this is a `@holochain/client` bug. Should somebody log it there?

**Comment by jost-s** [comment]
Hi @pospi, the next iteration of Tryorama is released. You can set the timeout of the Admin websocket now like this for example:
```ts
tape("Install large hApp bundle", async (t) => {
  await runScenario(
    async (scenario: Scenario) => {
      await scenario.addPlayersWithHappBundles([largeHappBundle]);
    },
    true,
    { timeout: 30000 }
  );
});
```

**Comment by pospi** [comment]
Exciting! Thanks for letting me know.

Sent from ProtonMail mobile

-------- Original Message --------
