### ISSUE TITLE
unless making this `.on` instead of `.once` all the conductor logs are swallowed here

### ISSUE THREAD

**Issue by Connoropolous** [holochain/tryorama#124]
https://github.com/holochain/tryorama/blob/488d3fff6c43daf848f9229ca20db2595f5d3390/ts/src/local/conductor.ts#L273-L275

**Comment by Connoropolous** [comment]
I also changed it to `logger.info`  . Preferable of course would be an upstream fix of some kind to route things not through stderr. I'm not sure why they're coming here

**Comment by jost-s** [comment]
Thanks for spotting that, @Connoropolous. I agree to it all and also have no idea why it comes out on stderr.
I'll release a fix promptly.

**Comment by jost-s** [comment]
This looks right https://github.com/holochain/holochain/blob/develop/crates/hc_sandbox/src/run.rs#L99

So perhaps it's further up in the `holochain` command.

@abe-njama I'll add this to the backlog.

**Comment by Connoropolous** [comment]
sure yes. I made the text prefix for stderr "conductor log" and used "logger.info"
Here's one: 

```
18:55:21 [Tryorama - Local Conductor] info: conductor log: Jun 15 18:55:21.452  INFO kitsune_p2p_types::metrics: sys_info=MetricSysInfo { used_mem_kb: 1596555, proc_cpu_usage_pct_1000: 24463, tx_bytes_per_sec: 409, rx_bytes_per_sec: 1843, sends_per_sec: 0, recvs_per_sec: 0, tokio_task_count: 7, avg_pool_buf_release_size: 0, avg_api_req_res_elapsed_ms: 0 }
```

**Comment by Connoropolous** [comment]
groovy, thanks @jost-s. You are on it!
