### ISSUE TITLE
the logging situation

### ISSUE THREAD

**Issue by Connoropolous** [holochain/tryorama#128]
building on the learnings from https://github.com/holochain/tryorama/issues/124...

Context, when updating to latest `tryorama` we (working on hREA) "lost" our wasm debug logs. We couldn't find them. I had to dig through source code and other things to figure out what to do to get them back, which I've only just managed now. My solution was to set TRYORAMA_LOG_LEVEL=debug. This struck me as non-obvious and I don't think I've seen it anywhere in the README or documentation but please let me know if I'm wrong about that.

Once I'd set, I was able to see my wasm log through tryorama again:
```
14:11:56 [Tryorama - Local Conductor] debug: starting conductor
Jun 20 14:11:56.088 DEBUG wasm_trace: hc_zome_rea_agreement:zomes/rea_agreement/zome/src/lib.rs:37 WARGH
```

The logging situation is pretty confusing. `starting conductor` here doesn't make sense since it appears for any logged line, coming through `stdout`. There is also the question/issue of the logging level. I think `stdout` and `stderr` logs should both share the same logging level since they're not otherwise semantically meaningful. The logging level of `tryorama` I think is having no impact on or respect for the logging level of `holochain` itself (aside the stdout/stderr issue). 

https://github.com/holochain/tryorama/blob/618bbab7f08cf37bba24f163d0f59029910a4d67/ts/src/local/conductor.ts#L251-L252

https://github.com/holochain/tryorama/blob/618bbab7f08cf37bba24f163d0f59029910a4d67/ts/src/local/conductor.ts#L273-L274

Related somewhat: https://github.com/holochain/holochain/issues/1449

**Comment by jost-s** [comment]
@Connoropolous Thank you for the diligent issues and tracing the problems up and downstream. I spent way more time on the TryCP logs and was in a rush when working on the local conductor logs.

I've fixed the `conductor startup` log issue and updated the readme with the env var.

I don't know about the log level, as I don't have good examples of what the log outputs coming from `hc sandbox` look like. Generally I think `stderr.on("data")` should output to `info` or `error`, whereas `stdout.on("data")` should output to `verbose` or `debug`. Errors need to be logged always, whereas what else comes from the conductor should be logs that are only required when details of the conductor process need to be inspected.

I would wait for the upstream holochain log issue to be fixed before modifying the log levels in Tryorama. What do you think?

**Comment by jost-s** [comment]
I'd consider logs from the WASM as debug output that you want to see when you're developing something. Once development is finished and with the tests running on a CI, it doesn't need to show. You'd come back to it when experiencing an error and wanting to look into the issue, when you set the log level to debug manually again.

Do you agree?

**Comment by Connoropolous** [comment]
So, there is a need to be able to see WASM_LOG type debug logs while running tryorama. For that we apparently need the `stdout` feed to be piped through, fed to the console again by tryorama

**Comment by jost-s** [comment]
I agree, so to be clear, WASM_LOGs should always be printed at log level `debug`, but not at `info` IMO.

**Comment by Connoropolous** [comment]
Ah I see

**Comment by jost-s** [comment]
Coming back to this now, I've run a few tests where I output traces from a zome. Regardless of the level of the trace, they're all output in the console when running a test with Tryorama, without the need to set an env var or the like.

> I agree, so to be clear, WASM_LOGs should always be printed at log level `debug`, but not at `info` IMO.

I disagree with myself here and think that all wasm logs should be printed at info level. As this is how it is wired right now, I'll close this issue.
