### ISSUE TITLE
Stabilising latest version API and ensuring Holochain core compatibility

### ISSUE THREAD

**Issue by pospi** [holochain/tryorama#13]
Hey @maackle (: I've been having issues upgrading to `0.2.0-rc.2` (config doesn't seem to work as it's documented), but I can't find the source code of that version anywhere to check against... it doesn't seem to be on `master` here.

I haven't had debug output in tests for a while now and I was hoping upgrading would fix the issue. But the code I'm looking at that came from NPM seems to have changed dramatically or be midway through an edit- I can't use `genConfigArgs` in the conductor anymore. How should I go about dynamically injecting `zomePort` now? Is this a semi-stable API I'm looking at, or will the next version be different?

**Comment by maackle** [comment]
Hey @pospi, 0.2.x comes with tons of breaking changes! I shouldn't have called it `rc` since I'm still working on the documentation. I would stick to 0.1.x for now.

Maybe you could help me work through some usability issues though, since the proposed changes are drastic. You should still be able to use genConfigArgs, now roughly equivalent `ConfigSeedArgs`, but the way data flows is changing. Can you describe your use case?

**Comment by pospi** [comment]
Done, thanks! And sure, the use-case is this- https://github.com/holo-rea/holo-rea/blob/01857a3/test/init.js#L77

Basically, I need to be able to configure the zome port to pass it to `hc-web-client` in order to run integration tests against the GraphQL API that my app exposes.

**Comment by pospi** [comment]
I don't suppose you have a config example that you know `hdk::debug` output works with? My team is currently at a standstill without being able to debug their tests...

**Comment by maackle** [comment]
@pospi for 0.1.x, try this? https://github.com/holochain/holochain-rust/blob/e35c356a264eec92d41e84f135cbf2f96287178c/stress-test/src/index.ts#L38

**Comment by pospi** [comment]
This works, thanks! N3H is still very noisy, but I can live with that so long as I can grep for log string prefixes in the output (:

I'll leave this issue open for others wondering about 0.2.x for now, feel free to close whenever you feel it's appropriate.

**Comment by maackle** [comment]
@pospi you will probably have a better experience with sim2h as the network backend. In a holochain-rust nix-shell you can run `hc-sim2h-server-install` which will build a `sim2h_server` binary, which you can run locally when running your tests. Just use this `network` config:

```js
network: {
    type: 'sim2h',
    sim2h_url: 'ws://localhost:9000'
}
```

**Comment by pospi** [comment]
Hrmm I guess that's a very new command, I don't have it yet in `0.0.38-alpha14`

**Comment by pospi** [comment]
Following on from this suggestion in core: https://github.com/holochain/holochain-rust/issues/1936#issuecomment-563489977

Have upgraded to `0.3.0-rc.3` and most things seem to be working OK. Test running gets more complicated with the need to run the sim2h server, but that is temporary so no big deal.

I've tried to set a custom websocket port for the conductor so that other clients can be integrated with the DNA in integration tests, but it looks like there are bugs in the code that prevent this from working. Still a mystery as to where the official development of this package is happening- I can't find the code I'm pulling from NPM anywhere in this repo, but I have been able to narrow things down locally.

First let's make sure I am attempting this correctly- seems like I need to [inject the custom zome port](https://github.com/holo-rea/holo-rea/blob/7288f0a/test/init.js#L59) within the config handler function rather than orchestrator config now. The parameter name is `interfacePort` rather than `zomePort`. Seems fine- the data being generated by `ScenarioApi` in `const configJson = await configSeed(configSeedArgs)` appears to have the correct port assignments reflected in `configJson`.

Only issue is you are doing `const { configDir, interfacePort } = configSeedArgs` a few lines lower down, which means you're pulling `interfacePort` from the original config, before it's had a chance to be intercepted and modified by my custom config handler. The end result is that the `Player` being constructed is listening on the unmodified port, it never gets a connection, and my tests hang.

**Comment by maackle** [comment]
I'll look into the port handling issue separately, but any version with a dash in it is considered "unstable", and is not in master. When a stable version is released, it gets merged to master. I just cut `0.2.1` and merged that into master today. I recommended you to use an unstable version, so that's why you're not seeing it in master. `0.3.0-x` is not yet stable, but development on it is being tracked on the [`v0.3.0` branch](https://github.com/holochain/tryorama/tree/v0.3.0). @pospi

**Comment by pospi** [comment]
Thanks @maackle. It's annoying that Github only searches the master branch... wish it would match code in the tips of feature branches too...

**Comment by pospi** [comment]
Just pinging here to say that I've tried `0.3.1` & `0.3.2-dev.2`, and neither fixes the `zomePort` issue. I'll close this one and open a new thread.
