### ISSUE TITLE
tryorama is not equipped for `network_seed` instead of `uid`

### ISSUE THREAD

**Issue by Connoropolous** [holochain/tryorama#145]
I think it should have been brought up to date with this PR
https://github.com/holochain/tryorama/pull/144
but that part of things got missed. 
I would like to see hREA update and use the `network_seed` feature

Relatedly it should be using @holochain/client 0.8.0 I think?

**Comment by Connoropolous** [comment]
ping @jost-s

**Comment by jost-s** [comment]
Thanks for reporting this, Connor. I'll fix the name change and upgrade to holochain client shortly.
