### ISSUE TITLE
Unable to override custom zome port for players

### ISSUE THREAD

**Issue by pospi** [holochain/tryorama#16]
Since the 0.2.x branch I can't use `genConfigArgs` in the conductor anymore. How should I go about dynamically injecting `zomePort` now?

The use-case is that I need to be able to configure the zome port to pass it to `hc-web-client` in order to run integration tests against the GraphQL API that my app exposes.

First let's make sure I am attempting this correctly- seems like I need to [inject the custom zome port](https://github.com/holo-rea/holo-rea/blob/7288f0a/test/init.js#L59) within the config handler function rather than orchestrator config now. The parameter name is `interfacePort` rather than `zomePort`. Seems fine- the data being generated by `ScenarioApi` in `const configJson = await configSeed(configSeedArgs)` appears to have the correct port assignments reflected in `configJson`.

Only issue is you are doing `const { configDir, interfacePort } = configSeedArgs` a few lines lower down, which means you're pulling `interfacePort` from the original config, before it's had a chance to be intercepted and modified by my custom config handler. The end result is that the `Player` being constructed is listening on the unmodified port, it never gets a connection, and my tests hang.

**Comment by maackle** [comment]
Hey @pospi, good catch, and thanks for finding and pointing out the cause of the problem as well!

I just started [a branch for v0.3.2](https://github.com/holochain/tryorama/tree/v0.3.2) that should fix this. The integration tests are broken so I have to fix them first so can't cut a release, but you could try pointing to this branch in your package.json with a git dependency and see if that works for you.

**Comment by pospi** [comment]
Thanks for pushing ahead on this for me- it's actually blocking me from upgrading Holochain & getting CI working, so the interest is appreciated (:

Set the git URL as a dependency and got `Cannot find module './config/builder'` out of `lib/index.js`.

So then cd'd to the module directory and tried `npm run build`... got these errors:

```
src/api.ts:220:5 - error TS2322: Type '[{}, {}, {}, {}, {}, {}, {}, {}, {}, {}]' is not assignable to type 'boolean[]'.
  Type '{}' is not assignable to type 'boolean'.

220     return localKills
        ~~~~~~~~~~~~~~~~~

src/config/gen.ts:49:27 - error TS2345: Argument of type 'Fort<({ id: string; agent: { id: string; name: string; keystore_file: string; public_address: string; } & { test_agent?: boolean | undefined; }; dna: { id: string; file: string; } & { hash?: string | undefined; uuid?: string | undefined; }; } & { ...; })[] | { ...; }>' is not assignable to parameter of type '({ id: string; agent: { id: string; name: string; keystore_file: string; public_address: string; } & { test_agent?: boolean | undefined; }; dna: { id: string; file: string; } & { hash?: string | undefined; uuid?: string | undefined; }; } & { ...; })[] | { ...; }'.
  Type '(ConfigSeedArgs: any) => ({ id: string; agent: { id: string; name: string; keystore_file: string; public_address: string; } & { test_agent?: boolean | undefined; }; dna: { id: string; file: string; } & { ...; }; } & { ...; })[] | { ...; }' is not assignable to type '({ id: string; agent: { id: string; name: string; keystore_file: string; public_address: string; } & { test_agent?: boolean | undefined; }; dna: { id: string; file: string; } & { hash?: string | undefined; uuid?: string | undefined; }; } & { ...; })[] | { ...; }'.
    Type '(ConfigSeedArgs: any) => ({ id: string; agent: { id: string; name: string; keystore_file: string; public_address: string; } & { test_agent?: boolean | undefined; }; dna: { id: string; file: string; } & { ...; }; } & { ...; })[] | { ...; }' is not assignable to type '{ [x: string]: { id: string; file: string; } & { hash?: string | undefined; uuid?: string | undefined; }; }'.
      Index signature is missing in type '(ConfigSeedArgs: any) => ({ id: string; agent: { id: string; name: string; keystore_file: string; public_address: string; } & { test_agent?: boolean | undefined; }; dna: { id: string; file: string; } & { ...; }; } & { ...; })[] | { ...; }'.

49     validateInstancesType(instancesFort)
                             ~~~~~~~~~~~~~

src/config/gen.ts:60:26 - error TS2345: Argument of type '({ id: string; agent: { id: string; name: string; keystore_file: string; public_address: string; } & { test_agent?: boolean | undefined; }; dna: { id: string; file: string; } & { hash?: string | undefined; uuid?: string | undefined; }; } & { ...; })[] | { ...; }' is not assignable to parameter of type '{ [x: string]: { id: string; file: string; } & { hash?: string | undefined; uuid?: string | undefined; }; }'.
  Type '({ id: string; agent: { id: string; name: string; keystore_file: string; public_address: string; } & { test_agent?: boolean | undefined; }; dna: { id: string; file: string; } & { hash?: string | undefined; uuid?: string | undefined; }; } & { ...; })[]' is not assignable to type '{ [x: string]: { id: string; file: string; } & { hash?: string | undefined; uuid?: string | undefined; }; }'.
    Index signature is missing in type '({ id: string; agent: { id: string; name: string; keystore_file: string; public_address: string; } & { test_agent?: boolean | undefined; }; dna: { id: string; file: string; } & { hash?: string | undefined; uuid?: string | undefined; }; } & { ...; })[]'.

60       : desugarInstances(instancesData, args)
                            ~~~~~~~~~~~~~

src/types.ts:58:31 - error TS2349: Cannot invoke an expression whose type lacks a call signature. Type 'Fort<T>' has no compatible call signatures.

58   await (_.isFunction(fort) ? fort(args) : _.cloneDeep(fort))
```

Following that a very long list of problems in `react` & `react-dom` that are hopefully (but maybe not) just warnings that won't affect compilation. Either way after running this I seem to get quite a few new files in `/lib`, so it looks like it's at least partially succeeding.

Either way, I am still getting the hang so I guess there are still fixes to make. I'll take a look...

> FYI- the idiomatic way to set up `package.json` now is to use the `prepare` command instead of `build` (see [here](https://docs.npmjs.com/misc/scripts))- this would also allow me to use the package straight from git without having to put a manual build step workaround in my workspace.

**Comment by pospi** [comment]
Value looks fine in debugging actually- I think it's my issue... one sec...

**Comment by pospi** [comment]
@maackle please note the above comments RE `package.json` though, would be good to have moving forward^

**Comment by maackle** [comment]
@pospi thank you for all your real-world battle testing of tryorama and careful diagnosis! :pray:

I notice in your issues you often pinpoint exactly where the problem is in the tryorama code (which is so helpful), and in those cases I welcome you to also open a PR that points out or fixes the problem, which would unblock you immediately (by letting you point to your own branch) and also provide a quicker path to getting it merged upstream. Especially for this quick fix to package.json you just proposed, since that fix is precisely around making it easier to work directly from a git branch instead of a proper npm release.

I welcome your collaboration, especially since you use tryorama extensively and understand its needs well. If you so choose!

I'll still get around to this at some point if you don't first.

**Comment by pospi** [comment]
Point taken (: I think I was avoiding that as I wasn't sure which branches
were active early on... But now that I do, happy to submit PRs!
