### ISSUE TITLE
Tryorama not using up-to-date nor pinned @holochain/client

### ISSUE THREAD

**Issue by Connoropolous** [holochain/tryorama#160]
Also, unless @holochain/client starts following proper semver for releases, you probably don't want the `^` which take `0.12.X` whatevers recent, breaking changes  or not.

https://github.com/holochain/tryorama/blob/706955a475e1f4f6456a76734b8dc886ef4891d9/package.json#L48

**Comment by Connoropolous** [comment]
@jost-s

**Comment by jost-s** [comment]
With the Holochain beta release 0.1.0 the JS client and Tryorama are back to following semver. The version bump of the JS client was symbolic, it didn't involve functional changes for Tryorama.
