### ISSUE TITLE
console logging not clear

### ISSUE THREAD

**Issue by nphias** [holochain/tryorama#164]
console.log no longer works for me within the tests..

also its not clear from the documentation how you set the wasm log level?
 TRYORAMA_LOG_LEVEL=debug node test.js  ?

i just do npm test from the command line..  
should the log level not be a property one can set in the test scripts?

**Comment by jost-s** [comment]
Adapted to your command, it's `TRYORAMA_LOG_LEVEL=debug npm test`.

Also see the message above your's on discord https://discord.com/channels/727959104777224303/776952534873931806/1072575344336437268

On Monday I'll release.

**Comment by nphias** [comment]
doesnt make a difference if run the command you suggest...  console logs are lost.. its much harder to diagnose what is going on when your tests fail without being able to log intermediate states and steps.  even a file log would help

**Comment by jost-s** [comment]
Then I need a repro. I've test this this week and it works for me.

Your npm test is calling another `npm t -w tests`, which in turn calls some foreach stuff - perhaps that spawns a new shell without the log level env var set?

**Comment by nphias** [comment]
the test above is from the scaffolding tool with the forum template example ..  just added one console.log to a test scenario.    also tried with another happ using a single test scenario..

**Comment by nphias** [comment]
ok the scaffolding tool has been updated and logging works again

**Comment by jost-s** [comment]
I'm glad it's resolved, although it's still mysterious how these logs can have been swallowed.
