### ISSUE TITLE
executing command runs indefinitely

### ISSUE THREAD

**Issue by nphias** [holochain/tryorama#165]
executing command  ... path-to-test-file   sometimes runs indefinitely ... race condition?
more console logging about what its actually doing would be useful

**Comment by jost-s** [comment]
Well, that's what the log level is intended for. I'll look into how logs can be distributed better across the log levels.

**Comment by jost-s** [comment]
Otherwise I need a concrete example with that indefinitely running command.

**Comment by jost-s** [comment]
A command may seem to run indefinitely if the conductor is not shut down or cleaned up at the end of a test. Is that the reason?

**Comment by jost-s** [comment]
I'm going to close this issue. If it re-appears, please re-open.
