### ISSUE TITLE
Tryorama sample code does not use alice.instance("xxx").agentAddress

### ISSUE THREAD

**Issue by zaunders** [holochain/tryorama#19]
We tried using the sample code with alice.agentAddress('instance') which doesn't seem to work.

Looking at guillems code,  alice.instance("mail").agentAddress seems to be the proper function

**Comment by maackle** [comment]
@zaunders where did you find that sample code?

**Comment by guillemcordoba** [comment]
It's in the README, Sample Usage section:

```
  // now you can make zome calls,
  await alice.call('chat', 'messages', 'direct_message', {
    content: 'hello world',
    target: carol.agentAddress('chat')
  })
```

**Comment by maackle** [comment]
Thanks for pointing that out!

**Comment by zaunders** [comment]
Thanks Guillem for pointing to where! :)
