### ISSUE TITLE
how to set loglevel verbosity

### ISSUE THREAD

**Issue by nphias** [holochain/tryorama#21]
using the latest version  "@holochain/tryorama": "^0.3.2-dev.2"

in the readme file it says switching off logging is a config setting: 
`const commonConfig = Config.gen(
  {
    chat: Config.dna('path/to/chat.dna.json')
  },
  {
    logger: Config.logger(false)
  }
)`

i get an error that the 'type' field is missing with this config
i imagine it should be something like  {type:'error'}   but that doesnt work for me either.

**Comment by maackle** [comment]
Oops, it was a mistake to let that version get tagged as the latest version. Can you try it with `0.3.1`?

**Comment by nphias** [comment]
same error

20:31:11 info: 
★★★ [[[CONDUCTOR alice]]]
★ Error while trying to boot from config: IoError("Error loading configuration: missing field `type` for key `logger`")
★ 
20:31:11 [tryorama] info: conductor 'alice' exited with code 0
not ok 1 Conductor exited before starting interface (code 0)

**Comment by milkyklim** [comment]
Seems related. 

If I set different verbosity level for logger, e.g. `error` or `info`, I get the same output. Using version `"@holochain/tryorama": "^0.3.0"`.

**Comment by maackle** [comment]
Hey @nphias, @milkyklim this was a simple bug of invalid config being generated, it should be fixed in `0.3.2-dev.3` which I just published.

**Comment by nphias** [comment]
oh nice.. will try it and close the issue if it works..
.. .One other thing on the wish list would be a config to filter out debug messages that are about the state the conductor and network.... from debug messages that tell us zome interaction and testing..

**Comment by milkyklim** [comment]
Works on my side, thanks for the fix.

**Comment by nphias** [comment]
its not working for me ... @milkyklim can you paste your code?
i guess it should be something like 
```
,{
    logger: Config.logger({level:"error"})
   }
```

**Comment by milkyklim** [comment]
``` 
const config = Config.gen(
  {
   hello_holo: dna,
  },
  {
    logger: Config.logger(false),
  },
);
```

**Comment by milkyklim** [comment]
@nphias dictionary key is `type`, not `level`.

**Comment by nphias** [comment]
ok got it working..  i understand ... it moderates logging that the core spits out not test logs
```
const mainConfig = Config.gen({
    logger: Config.logger({type:"error"})
  })
```
or to just turn off all:
```
const mainConfig = Config.gen({
    logger: Config.logger(false)
  })
```
