### ISSUE TITLE
How to initialize app with alice as progenitor

### ISSUE THREAD

**Issue by guillemcordoba** [holochain/tryorama#23]
Hi! I'm developing the tests for https://github.com/eyss/hc_zome_roles. In this library, the use of the progenitor pattern is required. I know how to get the property from inside the DNA code, but how can I initialize the DNA in tryorama with alice as its progenitor?

I only need alice's address as a progenitor property of the DNA. Thanks!

**Comment by jost-s** [comment]
closing

**Comment by guillemcordoba** [comment]
Oh shoot I didn't get notified about this.

The progenitor pattern is a happ design pattern, where one of the properties of the DNA is the agent public key of the "progenitor" (you can think of the progenitor as the "admin" of the DNA). That agent would have a special role in the network, with special abilities that others don't have. 

I have to try this one out in the next week or so, will post here if this is still not possible and reopen.

**Comment by jost-s** [comment]
@guillemcordoba Alright, great. Thanks for clarifying. You might have to watch this repo in order to get notified about activities.
