### ISSUE TITLE
Cleaning up debug messages

### ISSUE THREAD

**Issue by nimser** [holochain/tryorama#24]
I'm getting a lot of messages of the following structure when I run tests:

`00:00:00 [tryorama: tryorama conductor bob] debug: ...`
or
`00:00:00 [tryorama] info: ...`
as well as

```
00:00:00 info:
☸☸☸ [[[CONDUCTOR alice]]]
☸ Successfully loaded 1 instance configurations
☸ Starting instances...
☸ Start all instances
☸ Starting instance "course_dna"...
```

I find this clutters my test output and makes it hard to read what the results of my actual tests are.
I throught configuring the logger would help, but even after configuring the logger to `error`, I'm still getting the `debug` and `info` messages.

Here's what I tried in the conductor statement:

```javascript
const conductorConfig = Config.gen(
  { course_dna: dna },
  {
    network: {
      type: "sim2h",
      sim2h_url: "ws://localhost:9000"
    },
    logger: Config.logger({ type: "error" }),
  }
);
```

and in the orchestrator statement:

```javascript
const orchestrator = new Orchestrator({
  middleware: combine(
    tapeExecutor(require("tape")),
    localOnly
  ),
  globalConfig: {
    logger: { type: "error" }
  }
});
```

Note that following recommendations [here](https://forum.holochain.org/t/tryorama-debug-info-output-making-it-impossible-to-review-tests/1782), I've been using `^0.3.0-rc.3` to try solving the issue, to no avail.

Am I missing something?

**Comment by maackle** [comment]
@niwolive first of all, looks like your syntax is from an older version, `globalConfig` went away in favor of an extra argument to `Config.gen`.

Can you see if this section of the README helps? https://github.com/holochain/tryorama#simple-config-with-the-config-helper. In particular, try something like this:

```js
const commonConfig = Config.gen(
  {
    chat: Config.dna('path/to/chat.dna.json')
  },
  {
    logger: Config.logger(false)
  }
)
```

**Comment by jost-s** [comment]
Closing.
