### ISSUE TITLE
Too few JSDoc & comments

### ISSUE THREAD

**Issue by guillempuche** [holochain/tryorama#26]
It's difficult to understand the code if it isn't documented. Especially, the exported methods/variables and methods of the classes.

Example of a [method of the class `Player`](https://github.com/holochain/tryorama/blob/master/src/player.ts#L66): `call` method should have an explanation about what `args` are necessary and why they're needed.

**Comment by jost-s** [comment]
@guillempuche There's complete documentation now, please have a look.
