### ISSUE TITLE
Tryorama RSM -  emit_signal Testing

### ISSUE THREAD

**Issue by JettTech** [holochain/tryorama#40]
### Feature Request
 - Add method for emit_signal testing

Currently, there is no method for testing emit_signals within the dna.  Emit signals return a null value and as such, require additional tooling to listen to network calls and read signal data returned to the conductor for proper testing at the dna level.

**Comment by Connoropolous** [comment]
I will "pile on" here... I've felt a great need for this as well

**Comment by zippy** [comment]
added in #54
