### ISSUE TITLE
[RSM] Version mistmatch with @holochain/conductor-api

### ISSUE THREAD

**Issue by guillemcordoba** [holochain/tryorama#41]
When installing tryorama and running `npm test`, this error gets returned:

`TypeError: cell_data is not iterable`

Updating to the latest version of `@holochain/conductor-api` IN GITHUB fixes the issue. Once a new version of @holochain/conductor-api gets released, tryorama can be updated to point to the newer version on npm.

For now, workaround for developers: install the conductor-api from github in your `test/package.json` with:

`npm install https://github.com/holochain/holochain-conductor-api`

**Comment by zippy** [comment]
Thanks @guillemcordoba, just ran into this myself this morning!

**Comment by tatssato** [comment]
Thanks @guillemcordoba!!
