### ISSUE TITLE
Some unhandled promise exceptions cause loss of output

### ISSUE THREAD

**Issue by maackle** [holochain/tryorama#5]
From a holochain-rust discussion:

> FWIW these kinds of `Unreachable` crashes are a problem in a lot of Diorama setups due to the way tests have been wired for unhandled promise rejections. Implementors should probably be advised to add a [short wait](https://github.com/holo-rea/holo-rea/commit/8ba1ccf16699af5164c28cf2eeca8d9acf55fc8c) before exiting the JS test runner as otherwise useful debug logs are often missed.

_Originally posted by @pospi in https://github.com/holochain/holochain-rust/issues/159#issuecomment-535337345_

**Comment by jost-s** [comment]
I suppose this no longer applies.
