### ISSUE TITLE
Documentation / examples of advanced `logger` configuration

### ISSUE THREAD

**Issue by pospi** [holochain/tryorama#7]
This new logger looks like it might have the capabilities I was craving with Diorama :D

Is it possible to configure it to:

- show only DNA logs output with `hdk::debug`; nothing else?
- show only DNA logs related to data writes?
- show only DNA logs related to data reads?
- show only DNA logs related to inter-DNA `call`s & signalling?

...and I guess optimally, combinations of all of the above & more?

**Comment by zippy** [comment]
Hey there @pospi!  Yout can do reg-ex matches for what you want:

``` js
const orchestrator = new Orchestrator({
    middleware,
    waiter: {
	softTimeout: 5000,
	hardTimeout: 10000,
    },
    globalConfig: {
	logger: {
            type: "debug",
            rules: {
		rules: [
                    {
			exclude: true,
			pattern: ".*parity.*"
                    },
                    {
			exclude: true,
			pattern: ".*mio.*"
                    },
                    {
			exclude: true,
			pattern: ".*tokio.*"
                    },
                    {
			exclude: true,
			pattern: ".*hyper.*"
                    },
                    {
			exclude: true,
			pattern: ".*rusoto_core.*"
                    },
                    {
			exclude: true,
			pattern: ".*want.*"
                    },
                    {
			exclude: true,
			pattern: ".*rpc.*"
                    }
		]
            },
            state_dump: true,
	},
	network: transport_config
    }
})
```

**Comment by zippy** [comment]
we should defintely provide some helpers in try-o-rama to make that easier.

**Comment by pospi** [comment]
Not sure these are working for me... I have just updated to latest core as well. With either configuration I still seem to be getting excessive log output.

Also no luck on getting the `N3H_QUIET` environment variable to work with my tests.

**Comment by pospi** [comment]
Further to that, the situation seems to be that debug output from `hdk::debug` is being suppressed, I have tried with the simple `logger: true` option and I'm not seeing anything.

My development workflow is sorta stalled now, pending some way of getting usable logs & debug output from tests :/

**Comment by lorenjohnson** [comment]
> My development workflow is sorta stalled now, pending some way of getting usable logs & debug output from tests :/

👍 I would really like to figure-out how to get `hdk::debug` calls through as well. It's roadblocking me atm as well.

**Comment by pospi** [comment]
Having no issues with this on the 0.3.x versions of tryorama and Holochain core >= 0.0.40-alpha1. Are [these instructions](https://github.com/holo-rea/holo-rea/blob/master/README.md#debugging) working for you? This seems to work fine with the complete absence of any `logger` settings in the config.

**Comment by lorenjohnson** [comment]
> Having no issues with this on the 0.3.x versions of tryorama and Holochain core >= 0.0.40-alpha1. Are [these instructions](https://github.com/holo-rea/holo-rea/blob/master/README.md#debugging) working for you? This seems to work fine with the complete absence of any `logger` settings in the config.

Hey @pospi! Yes--false alarm :) The issue in my case was that the Communities DNA I was working on was passing the tryorama / tape results through the `faucet` npm module which was making a very tidy test run but filtering out most all of the logging. Removed that and have now been configuring logging down to what I need.
