### ISSUE TITLE
Signals blocks rest of call execution for a conductor that has been `shutdown` and then `startup`

### ISSUE THREAD

**Issue by guillemcordoba** [holochain/tryorama#99]
See [this CI execution](https://github.com/eyss/elo/runs/4429327551?check_suite_focus=true), this is the [signal that does work](https://github.com/eyss/elo/blob/623f0965651c0d4d42bd5e65bd8459fe4fa3f259/mixin/src/game_result/unpublished.rs#L83), but then it actually blocks the rest of the function execution.

**Comment by jost-s** [comment]
Hi @guillemcordoba, the next iteration has been released. Please let me know if this is still an issue.
